### PR TITLE
Feature: Add files for example project to base new APIS Ontologies apps on

### PR DESCRIPTION
**Pull request by koeaw**
Files are based on files of existing APIS Ontologies apps, esp. Jelinek. A number of files were updated primarily with regard to formatting, but partly (minimally) also content-wise: e.g. protocol portions of URLs were changed from `http` to `https` throughout (_without_ having tested they work; it is assumed that in 2022, public databases can be queried securely).

`server_settings.py` was refactored significantly with regard to structure/formatting, code comments, partly also default values, but likely needs to be modified further:
* all settings should be documented (README?)
* generic default values (or no values) should be used wherever possible,
* keys/secrets ought to be removed (and instructions on how to set them locally or via CI/CD added),
* any missing settings/variables of potential interest to devs should get (re)added and documented, e.g. values inherited from `base.py` which devs may want to override or add to.

`models.py` is very bare-bones and should have a few example entities/relationships added to it.

### CODE REVIEW

**Comment by koeaw** [comment]
Related: acdh-oeaw/apis-core-rdf#19

**Comment by steffres** [comment]
looks good and clarifies things. As for the various setting variables, I myself don't know which ones are legacy junk though, so let's rather keep it all for now and focus on morge urgent things.

**Comment by koeaw** [comment]
The newest changes to handling of Django's `SECRET_KEY` still need to be integrated into this PR...

**Comment by koeaw** [comment]
The directory which these files were meant to be added to was renamed and might have had other files added to it in the meantime (unclear as there's no PR which could conveniently be referenced).

Setting this to Draft since the changes in this PR will require review and adaptation (like file renames).

**Comment by koeaw** [comment]
Updated to latest `main` and reworked some, e.g. removed unknown settings from `server_settings.py`, updated how properties are created in `models.py`,...

**Pull request merged**
