### PR TITLE
Ms/create new api views

### PR DESCRIPTION
**Pull request by sennierer**
given the performance problems in jelinek project this adds a fti based search for the project

- it adds `SearchVectorFields` to the model classes, eg here: https://github.com/acdh-oeaw/apis-ontologies/commit/19ac3f0e8cd99ece8e1806f1687d90d31a9bdd1f#diff-c63aec0fe3961ef100cb74483ff386b21524cfe9c83251029231c10d274ee24cR23-R27
- it adds a ontology specific script to populate these indexes with data: https://github.com/acdh-oeaw/apis-ontologies/blob/ms/create_new_api_views/jelinek/ontology_specific_scripts/populate_indexes.py
- it adds a new endpoint that uses annotations to pull in all data from related tables that is needed to create the facets: https://github.com/acdh-oeaw/apis-ontologies/blob/ms/create_new_api_views/jelinek/jelinek_api_views.py#L181-L204
- it adds a filter that uses the new indexes to search in: https://github.com/acdh-oeaw/apis-ontologies/blob/ms/create_new_api_views/jelinek/jelinek_api_filters.py#L179-L193
- it adds serializers that create a serialization of the data (including overall result number and facets counts) that should be sufficient to create a results page without hitting the API again: https://github.com/acdh-oeaw/apis-ontologies/blob/ms/create_new_api_views/jelinek/jelinek_api_serializers.py#L453-L498
- adds migrations for the new fields

There are still some shortcomings/things to implement;
- drf_spectacular seems to break on the SearchVectorField, so swagger is not yet working in this PR
- facets are currently only implemented for persons, the rest of the facets need implementation along the lines of https://github.com/acdh-oeaw/apis-ontologies/blob/ms/create_new_api_views/jelinek/jelinek_api_serializers.py#L488-L497
- some of the data still might be missing in the serialization
- pagination is not implemented yet
- code redundancies need to be removed/fixed

### CODE REVIEW

**Comment by katharinawuensche** [comment]
Works great and super fast, thank you! I added the remaining search parameters and facets. 
The only problem we have now: the SearchVectorFields mess up the default api endpoints, e.g. `apis/api/ontology/e1_crm_entity` as well as the default views in the UI (error message: `AdHocEntityListFilter resolved field 'vector_column_e1' with 'exact' lookup to an unrecognized field type SearchVectorField`). Is there an easy way to fix this?

**Comment by katharinawuensche** [comment]
Solved the issue mentioned above by overriding `get_entity_list_filter()` (for `apis/entities` view) and renaming the vector fields to ..._set (for `apis/api` view). Not sure if this was the most elegant solution, do you think this could break something @sennierer?

**Comment by sennierer** [comment]
Without having tested this I dont think it will mess something up. The names of the vector fields were completely arbitrary chosen, so I dont see why renaming could do harm.

**Comment by sennierer** [comment]
obviously you would need to adjust the script for populating the index fields

**Review by katharinawuensche — APPROVED** [review]
Nice! I just removed some unused searchvectors in the subclasses of e1_crm_entity and made some minor adaptions. If it's up to me, we can merge the branch.

**Pull request merged**
